
package main.java.sigep.views;


import java.net.URL;
import javax.swing.ImageIcon;


/**
 *
 * @author marito
 */
public class Ayuda extends javax.swing.JDialog {
   
    private String result;
  
    /**
     * Creates new form Ayuda
     */
    public Ayuda(java.awt.Frame parent, boolean modal) {     
    
        super(parent, modal);
        initComponents();
        setColumns();
        URL url = getClass().getResource("/main/java/sigep/views/icons/zebra.png");
        setIconImage(new ImageIcon(url).getImage());
        result = ""; 
    }

    Ayuda(Precios aThis, boolean b, boolean b0) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public String getResult() {
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBusqueda = new javax.swing.JLabel();
        tfBusqueda = new javax.swing.JTextField();
        cbAvanzada = new javax.swing.JCheckBox();
        spResultado = new javax.swing.JScrollPane();
        tbResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbBusqueda.setText("Búsqueda");

        cbAvanzada.setText("Búsqueda Avanzada");

        tbResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod. Int.", "Cod. Barras", "Descripción", "Existencia", "Precio", "Existencia FH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spResultado.setViewportView(tbResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAvanzada))
                            .addComponent(lbBusqueda))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lbBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAvanzada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setColumns() {/*
        Properties props = new Properties();
        try (InputStream input = new FileInputStream("jdbc.conf")) {
            props.load(input);
        } catch (IOException ex) {
            System.out.println("Error! " + ex.getMessage());
        }
        
        //Oculto la columna existencia2 para sucursal distinta de casa central
        if (!props.getProperty("db", "").equalsIgnoreCase("ferreteria")) {
            tbResultado.removeColumn(tbResultado.getColumn("Existencia FH"));
        }*/
    }

    private void tfBusquedaKeyReleased(java.awt.event.KeyEvent evt) { /*                                      
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (!tfBusqueda.getText().isEmpty()) {
                    List<Productos> articulos = ArticuloDAO.getArticulos(tfBusqueda.getText(), cbAvanzada.isSelected());
                    if (articulos.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No hay resultados para mostrar", "Alerta!", JOptionPane.ERROR_MESSAGE);
                    } else {
                        DefaultTableModel model = (DefaultTableModel) tbResultado.getModel();
                        model.setRowCount(0);
                        for (Productos articulo : articulos) {
                            model.addRow(articulo.toObject(true));
                        }
                        tbResultado.requestFocus();
                        tbResultado.setRowSelectionInterval(0, 0);
                    }
                }
                break;
            case KeyEvent.VK_ESCAPE:
                setVisible(false);
                break;
        }*/
    }

    private void tbResultadoKeyReleased(java.awt.event.KeyEvent evt) { /*                                       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) tbResultado.getModel();
            if (model.getRowCount() > 0) {
                int row = tbResultado.convertRowIndexToModel(tbResultado.getSelectedRow());
                result = (String) model.getValueAt(row, 0);
                this.dispose();
            }
        }*/
    }                                       

    private void formKeyPressed(java.awt.event.KeyEvent evt) {/*                                
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dispose();
        }*/
    }                               

    private void tbResultadoKeyPressed(java.awt.event.KeyEvent evt) {  /*                                     
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
        }*/
    } 
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAvanzada;
    private javax.swing.JLabel lbBusqueda;
    private javax.swing.JScrollPane spResultado;
    private javax.swing.JTable tbResultado;
    private javax.swing.JTextField tfBusqueda;
    // End of variables declaration//GEN-END:variables
}
