
package main.java.sigep.views;

import java.io.IOException;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import main.java.sigep.model.dao.UsuariosDAO;
import main.java.sigep.model.dao.impl.UsuariosDAOImpl;
import main.java.sigep.model.entities.Usuarios;
import main.java.sigep.model.dao.RolesDAO;
import main.java.sigep.model.entities.Roles;

/**
 *
 * @author Marito
 */
public class Principal extends javax.swing.JFrame {
    
    private DecimalFormat formatter;
    private static String[] savedArgs;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();  
        
        objetcFrameControllers(false);//Inicializo los controles ocultos
        
        try {
            Properties properties = new Properties();
            properties.load(getClass().getResourceAsStream("/resources/Main.properties"));
            setTitle("SIGEP 1.0." + properties.getProperty("Application.revision")
                    + "." + properties.getProperty("Application.buildnumber"));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        
        URL url = getClass().getResource("/main/java/sigep/views/icons/zebra.png");
        setIconImage(new ImageIcon(url).getImage());
        formatter = new DecimalFormat("0.00");

    }
    
  
    private void showMenu(boolean tf) {
        jmArchivo.setVisible(tf);
        jmImpresiones.setVisible(tf);
        jmReportes.setVisible(tf);
    }
    
    private void showMenuRol(int rol) {
        
        if (rol == 1){
            jmArchivo.setVisible(true);
            
        }
        else{
        
            jmArchivo.setVisible(true);
        }
        //Permisos comunes a todos los perfiles
        jmImpresiones.setVisible(true);
        jmReportes.setVisible(true);
    }
    
    private void  objetcFrameControllers(boolean estado){
        lbUsuariovalidado.setVisible(estado);
        lbRolDeUsuario.setVisible(estado);
        
        showMenu(estado); // inico con los menues desactivados
        
        txtUsuario.setEnabled(!estado);
        jpPassword.setEnabled(!estado);
    
    };
    
    private void exitApplication() {
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0); // Salir de la aplicación
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jpPassword = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblIniciarSesion = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblUserpng = new javax.swing.JLabel();
        lbUsuariovalidado = new javax.swing.JLabel();
        lbRolDeUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiUsuarios = new javax.swing.JMenuItem();
        jmiPermisos = new javax.swing.JMenuItem();
        jmImpresiones = new javax.swing.JMenu();
        jmiPrecios = new javax.swing.JMenuItem();
        jmiNovedades = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmiListadoNovedades = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Contraseña");

        btnIngresar.setBackground(new java.awt.Color(0, 204, 204));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jpPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Inicion de Sesión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario)
                    .addComponent(jpPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIniciarSesion)
                .addGap(42, 42, 42)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addContainerGap())
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("<html>SISTEMA INTEGRAL DE<br> GESTION Y ETIQUETADO DE PRODUCTOS</html>");

        lblUserpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N

        jmArchivo.setText("Archivo");

        jmiUsuarios.setText("Gestion de Usuario");
        jmiUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuariosActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiUsuarios);

        jmiPermisos.setText("Gestion de Permisos");
        jmiPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPermisosActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiPermisos);

        jMenuBar1.add(jmArchivo);

        jmImpresiones.setText("Impresiones");

        jmiPrecios.setText("Consulta de Precios");
        jmiPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPreciosActionPerformed(evt);
            }
        });
        jmImpresiones.add(jmiPrecios);

        jmiNovedades.setText("Novedades");
        jmImpresiones.add(jmiNovedades);

        jMenuBar1.add(jmImpresiones);

        jmReportes.setText("Reportes");

        jmiListadoNovedades.setText("Listado de Novedades");
        jmiListadoNovedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListadoNovedadesActionPerformed(evt);
            }
        });
        jmReportes.add(jmiListadoNovedades);

        jMenuBar1.add(jmReportes);

        jmSalir.setText("Salir");
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUserpng)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbUsuariovalidado, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbRolDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUsuariovalidado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbRolDeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(lblUserpng)))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        
        
        //validar el usuario
        Integer idUsuario = Integer.parseInt(txtUsuario.getText());
        String contrasenia = new String(jpPassword.getPassword()); // Obtener la contraseña como cadena

        // Obtener el usuario desde la base de datos
        UsuariosDAO usuariosDAO = new UsuariosDAOImpl();
        Usuarios usuario = usuariosDAO.validarUsuario(idUsuario, contrasenia);
        
      
        if (usuario != null) {
            // Usuario encontrado y autenticado
           
            JOptionPane.showMessageDialog(this, "Bienvenido, " + usuario.getNombre());
 
            //Roles
            
            RolesDAO rolesDAO = new RolesDAO();
            Roles roles = rolesDAO.ObtenerRolUsuario(1);
            
            lbUsuariovalidado.setText("Usuario: "+usuario.getNombre());
            lbRolDeUsuario.setText("Rol: "+roles.getNombreRol());
            objetcFrameControllers(true);
            showMenuRol(usuario.getIdRol());
        } else {
            // Usuario o contraseña incorrectos
            JOptionPane.showMessageDialog(this, "Usuario o contraseña inválidos");
        }
        
        //Analizar permisos
        
        //Activar Menues
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jmiUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiUsuariosActionPerformed

    private void jmiPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPermisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiPermisosActionPerformed

    private void jmiListadoNovedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListadoNovedadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiListadoNovedadesActionPerformed

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
        // TODO add your handling code here:
        exitApplication();
    }//GEN-LAST:event_jmSalirMouseClicked

    private void jmiPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPreciosActionPerformed
        // TODO add your handling code here:
         abrirVentanaPrecios();
    }//GEN-LAST:event_jmiPreciosActionPerformed
    private void abrirVentanaPrecios() {
            // Crear una instancia de la ventana Precios
            Precios precios = new Precios();

            // Hacer visible la ventana Precios
            precios.setVisible(true);
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenu jmImpresiones;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiListadoNovedades;
    private javax.swing.JMenuItem jmiNovedades;
    private javax.swing.JMenuItem jmiPermisos;
    private javax.swing.JMenuItem jmiPrecios;
    private javax.swing.JMenuItem jmiUsuarios;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JLabel lbRolDeUsuario;
    private javax.swing.JLabel lbUsuariovalidado;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserpng;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
