package main.java.sigep.views;


//import main.java.sigep.controllers.Printer;
import main.java.sigep.model.dao.ProductosPOSDAO;
import main.java.sigep.model.entities.ProductosPOS;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.table.DefaultTableModel;
import main.java.sigep.controllers.Printer;
import main.java.sigep.model.dao.NovedadesDAO;
import main.java.sigep.model.entities.Etiquetas;
import main.java.sigep.model.entities.Novedades;


/**
 *
 * @author Marito
 */
public class Vnovedades extends javax.swing.JFrame {

    private PrintService printService;
    private Novedades novedadSeleccionada;
    private ProductosPOS articuloSeleccionado;
    private DecimalFormat formatter = new DecimalFormat("#,##0.00");
    private static String[] savedArgs;
    
    

    public Vnovedades() {
      
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        URL url = getClass().getResource("/main/java/sigep/views/icons/zebra.png");
        setIconImage(new ImageIcon(url).getImage());
        
       
        
        try {
            PrintService[] services = PrintServiceLookup.lookupPrintServices(null, null);
            int item = 0;
            
            for (PrintService service : services) {
                if (service.getName().toLowerCase().contains("zebra")) {
                    cbImpresora.addItem(service);
                    item++;
                    //break;
                }
            }
            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "No se pudo encontrar el servicio de impresión",
                    "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
 
        pLabels.addKeyListener(new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                int selected = 0;
                switch (e.getKeyCode()) {
                    case KeyEvent.VK_DOWN:
                        break;
                    case KeyEvent.VK_UP:
                        break;
                }
            }
        });
        
        List<Component> components = new ArrayList<>();
      
        components.add(pLabels);
        components.add(((DefaultEditor) spCantidad.getEditor()).getTextField());
        components.add(btImprimir);
        
        FocusPolicy focusPolicy = new FocusPolicy(components);
        setFocusTraversalPolicy(focusPolicy);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLabels = new javax.swing.ButtonGroup();
        lbCodigo = new javax.swing.JLabel();
        pLabels = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btImprimir = new javax.swing.JButton();
        spCantidad = new javax.swing.JSpinner();
        lbCantidad = new javax.swing.JLabel();
        lbImpresora = new javax.swing.JLabel();
        cbImpresora = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbResultado = new javax.swing.JTable();
        jFtffecha = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novedades"); // NOI18N
        setResizable(false);

        lbCodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCodigo.setText("Fecha de Novedad");

        pLabels.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pLabels.setFocusCycleRoot(true);
        pLabels.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pLabelsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pLabelsFocusLost(evt);
            }
        });

        jButton2.setText("Aplicar Filtros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secciones" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamentos" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Filtros");

        javax.swing.GroupLayout pLabelsLayout = new javax.swing.GroupLayout(pLabels);
        pLabels.setLayout(pLabelsLayout);
        pLabelsLayout.setHorizontalGroup(
            pLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLabelsLayout.createSequentialGroup()
                .addGroup(pLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 176, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pLabelsLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pLabelsLayout.setVerticalGroup(
            pLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btImprimir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/sigep/views/icons/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        spCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lbCantidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCantidad.setText("Cantidad");

        lbImpresora.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lbImpresora.setText("Impresora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbImpresora)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbImpresora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spCantidad)
                            .addComponent(btImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lbCantidad)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbImpresora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        tbResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Barras", "Descripcion", "Precio", "Motivo", "fecha", "operador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbResultado);

        jFtffecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-mm-dd"))));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFtffecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pLabels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFtffecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public String formatoFecha(){
    
        Date fecha = new Date();
        SimpleDateFormat fechaconFormato = new SimpleDateFormat("yyyy-mm-dd");
        return fechaconFormato.format(fecha);
    
    };
    
    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        if (articuloSeleccionado != null) {
            Etiquetas etiqueta = new Etiquetas(articuloSeleccionado);
            printService    = (PrintService)cbImpresora.getSelectedItem();
            
            
            if (printService != null) {
                Printer printer = new Printer(printService);
                int cantidad = (Integer) spCantidad.getValue();
              
                printer.print(etiqueta, cantidad, Printer.LabelType.STANDS);
                
                spCantidad.setValue(1);
            
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo encontrar la impresora",
                        "Alerta!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nada para imprimir",
                    "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void pLabelsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pLabelsFocusGained
       
    }//GEN-LAST:event_pLabelsFocusGained

    private void pLabelsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pLabelsFocusLost
        
    }//GEN-LAST:event_pLabelsFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscarArticulos();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    private void tfCodeKeyEnter() {
        try {
            novedadSeleccionada = NovedadesDAO.getArticuloNovedad("1", "2024/10/12");// El Articulo con la novedad
            if (novedadSeleccionada != null) {
                
                //aca buscamos si le dio enter en la tabla
                /*tfCodigo.setText(articuloSeleccionado.getCodigoInterno());
                tfCodigoBarras.setText(articuloSeleccionado.getCodigoBarra());
                tfDescripcion.setText(articuloSeleccionado.getDescripcion());
                
                if (articuloSeleccionado.getPrecioMinorista() != null) {
                    tfPrecio.setText(formatter.format(articuloSeleccionado.getPrecioMinorista()));
                } else {
                    tfExistencia.setText("0.00"); // O algún valor predeterminado
                }
                if (articuloSeleccionado.getExistencia() != null) {
                    tfExistencia.setText(formatter.format(articuloSeleccionado.getExistencia()));
                } else {
                    tfExistencia.setText("0.00"); // O algún valor predeterminado
                }*/
                
            } else {
                JOptionPane.showMessageDialog(null, "Artículo Inexistente",
                        "Alerta!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println("Error! " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "No hay conexión con la base de datos",
                    "Alerta!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void buscarArticulos() {
        String textoBusqueda = jFtffecha.getText();
      
                    List<Novedades> novedades = NovedadesDAO.getNovedades(jFtffecha.getText());
                    DefaultTableModel model = (DefaultTableModel) tbResultado.getModel();
                    model.setRowCount(0); // Limpio los resultados
                    
                    if (novedades.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No hay resultados para mostrar", "Alerta!", JOptionPane.ERROR_MESSAGE);
                    } else {
                        for (Novedades nove : novedades) {
                            model.addRow(nove.toObject());
                        }
                        tbResultado.requestFocus();
                        tbResultado.setRowSelectionInterval(0, 0);
                    }
       
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgLabels;
    private javax.swing.JButton btImprimir;
    private javax.swing.JComboBox cbImpresora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFtffecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbImpresora;
    private javax.swing.JPanel pLabels;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JTable tbResultado;
    // End of variables declaration//GEN-END:variables

}
